name: CICD


on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Build Docker Backed Image
        run: docker build -t sujan9748/amazon_scrapper_node_js ./api
      - name: Publish Backend image to Docker Hub
        run: docker push sujan9748/amazon_scrapper_node_js:latest
      - name: Build Docker Frontend Image
        run: docker build -t sujan9748/amazon_scrapper_react_js .
      - name: Publish image to Docker Hub
        run: docker push sujan9748/amazon_scrapper_react_js:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Remove all stopped containers
        run: docker container prune -f
      - name: Remove all unused images
        run: docker image prune -f
      - name: Pull Node Image from the Docker Hub
        run: docker pull sujan9748/amazon_scrapper_node_js:latest
      - name: Delete Old Node Container
        run: docker rm -f nodeContainer
      - name: Run docker Node container
        run: docker run -d -p 3001:3001 --name nodeContainer sujan9748/amazon_scrapper_node_js

      - name: Pull React Image from the Docker Hub
        run: docker pull sujan9748/amazon_scrapper_react_js:latest
      - name: Delete Old React Container
        run: docker rm -f reactContainer
      - name: Run docker React container
        run: docker run -d -p 3000:80 --name reactContainer sujan9748/amazon_scrapper_react_js
